from sqlalchemy import Column, Integer, String, Float, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database.session import Base


class Lead(Base):
    __tablename__ = "leads"

    id = Column(Integer, primary_key=True, index=True)
    search_id = Column(Integer, ForeignKey("searches.id"), index=True, nullable=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    
    company_name = Column(String(255), index=True, nullable=False)
    category = Column(String(255), index=True, nullable=False)
    phone = Column(String(100), default="Not Available")
    email = Column(String(255), default="Not Available", index=True)
    website = Column(String(500), default="Not Available")
    address = Column(Text, nullable=False)
    city = Column(String(100), index=True, nullable=True)
    state = Column(String(100), nullable=True)
    country = Column(String(100), default="India")
    country_code = Column(String(10), default="IN", index=True, nullable=True)
    postal_code = Column(String(50), default="Not Available")
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    rating = Column(Float, nullable=True, index=True)
    review_count = Column(Integer, default=0, index=True)
    business_status = Column(String(50), default="OPERATIONAL")
    
    # Core & Extended Profile Fields (35 Scraping Export Attributes)
    profile_url = Column(String(500), nullable=True)
    full_name = Column(String(255), nullable=True)
    first_name = Column(String(100), nullable=True)
    last_name = Column(String(100), nullable=True)
    title = Column(String(150), nullable=True)
    company_id = Column(String(100), nullable=True)
    company_url = Column(String(500), nullable=True)
    regular_company_url = Column(String(500), nullable=True)
    summary = Column(Text, nullable=True)
    title_description = Column(Text, nullable=True)
    industry = Column(String(255), nullable=True)
    company_location = Column(String(255), nullable=True)
    location = Column(String(255), nullable=True)
    duration_in_role = Column(String(100), nullable=True)
    duration_in_company = Column(String(100), nullable=True)
    past_experience_company_name = Column(String(255), nullable=True)
    past_experience_company_url = Column(String(500), nullable=True)
    past_experience_company_title = Column(String(255), nullable=True)
    past_experience_date = Column(String(100), nullable=True)
    past_experience_duration = Column(String(100), nullable=True)
    connection_degree = Column(String(50), nullable=True)
    profile_image_url = Column(String(500), nullable=True)
    shared_connections_count = Column(Integer, default=0, nullable=True)
    name = Column(String(255), nullable=True)
    vmid = Column(String(100), nullable=True)
    linkedin_profile_url = Column(String(500), nullable=True)
    is_premium = Column(Boolean, default=False, nullable=True)
    is_open_link = Column(Boolean, default=False, nullable=True)
    query = Column(String(255), nullable=True)
    timestamp = Column(String(100), nullable=True)
    phone_number = Column(String(100), nullable=True)
    default_profile_url = Column(String(500), nullable=True)
    search_account_profile_id = Column(String(100), nullable=True)
    search_account_profile_name = Column(String(255), nullable=True)
    sys3_status = Column(String(100), nullable=True)
    
    # Audit & Verification Fields
    provider_place_id = Column(String(255), index=True, nullable=True)
    places_source = Column(Boolean, default=True)
    is_demo = Column(Boolean, default=False, index=True)
    website_source_url = Column(String(500), nullable=True)
    email_source_url = Column(String(500), nullable=True)
    contact_page_url = Column(String(500), nullable=True)
    google_maps_url = Column(String(500), nullable=True)
    source = Column(String(100), default="Google Places API")
    
    lead_status = Column(String(50), default="New", index=True)
    notes = Column(Text, nullable=True)
    collected_at = Column(DateTime, default=datetime.utcnow, index=True)
    fetched_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="leads")
    search = relationship("Search", back_populates="leads")
